fixed bug about checking if log file is empty in cmt script

diff --git a/environment/defaults/bin/cmt b/environment/defaults/bin/cmt
--- a/environment/defaults/bin/cmt
+++ b/environment/defaults/bin/cmt
@@ -81,16 +81,14 @@ if [[ -f .git/MERGE_HEAD ]]; then
 fi
 
 # Check for empty log file
-if [[ ! -f $logFile ]]; then
-    emptyLogFile=0
-else
-    test -s ${logFile}
-    emptyLogFile=$?
-    echo emptyLogFile=${emptyLogFile}
+emptyLogFile=true
+if test -s ${logFile}; then
+    emptyLogFile=false
 fi
+echo emptyLogFile=${emptyLogFile}
 
 if [[ -n ${message} ]]; then
-    if [[ ${emptyLogFile} -ne 1 ]]; then
+    if [[ ${emptyLogFile} == false ]]; then
 	getAnswer "Git log file not empty: ${logFile}. Ignore and proceed?" || exit 0
     fi
     git commit -m "${message}"
@@ -108,9 +106,10 @@ else
     echo " "
     st  --untracked-files=no
     
-    if [[ ${emptyLogFile} -ne 1 ]]; then
-	echo "The log file is empty. Aborting."
-	exit 1
+    if [[ ${emptyLogFile} == true ]]; then
+        echo emptyLogFile=${emptyLogFile}
+        echo "The log file is empty. Aborting."
+        exit 1
     fi
 
     echo " "
