Summary: Details: 	1. environment/defaults/CodingTemplates/c++/templates.xml: updates. 	2. environment/defaults/bin/runPy: added support for -d option and code to create the __init__.py file, if it does not exist. 	3. environment/xcustoms/crpi.work/.ssh/known_hosts: bla.

diff --git a/environment/defaults/bin/runPy b/environment/defaults/bin/runPy
--- a/environment/defaults/bin/runPy
+++ b/environment/defaults/bin/runPy
@@ -16,6 +16,10 @@ cat << %%USAGE%%
        --roc
              Run a ROCARDIAN job, instead of the default RONIN one.
 
+       -d
+       --debug
+             Run the Debug build, instead of the Release one.
+
        -b branchName
        --branch branchName
              Run the code from the specified branch instead of master. This applies
@@ -37,7 +41,7 @@ cat << %%USAGE%%
 #----------------------------------------------
 # Main script
 #----------------------------------------------
-ARGS=$(getopt -o hb: -l "help,roc,branch:,codePath:,pythonPath:,printPaths" -n "$(basename ${0})" -- "$@")
+ARGS=$(getopt -o hdb: -l "help,roc,branch:,codePath:,pythonPath:,printPaths" -n "$(basename ${0})" -- "$@")
 
 # If wrong arguments, print usage and exit
 if [[ $? -ne 0 ]]; then
@@ -53,6 +57,7 @@ branchName=master
 pythonPath=''
 printPath=0
 codePath=${HOME}/code/drogon
+buildType=Release
 while true; do
     case ${1} in
 	-h|--help)
@@ -61,6 +66,10 @@ while true; do
 	    ;;
 	--roc)
 	    client=rocardian
+	    shift
+	    ;;
+	-d|--debug)
+	    buildType=Debug
 	    shift
 	    ;;
 	-b|--branch)
@@ -91,11 +100,23 @@ while true; do
 done
 
 # Create and check the lib path
-libPath=${HOME}/deploy/${branchName}/Release/lib
+libPath=${HOME}/deploy/${branchName}/${buildType}/lib
 if [[ ! -d ${libPath} ]]; then
    printf "Library path not found: ${libPath}\n"
    exit 1
 fi
+clientLibPath=${libPath}/${client}
+if [[ ! -d ${clientLibPath} ]]; then
+   printf "Client library path not found: ${clientLibPath}\n"
+   exit 1
+else
+    initFile=${clientLibPath}/__init__.py
+    if [[ ! -f ${initFile} ]]; then
+	touch ${initFile}
+    fi
+fi
+
+
 
 if [[ ! -d ${codePath} ]]; then
    printf "Code path not found: ${codePath}\n"
