Summary: improvements. Details: 	1. environment/defaults/bin/buildall: added code to copy the kfcData library in the install dir. 	2. environment/defaults/bin/toggleTrace: added functionality for taking options. 	3. environment/xcustoms/crpi.base/synergy.conf: updated setup.

diff --git a/environment/defaults/bin/toggleTrace b/environment/defaults/bin/toggleTrace
--- a/environment/defaults/bin/toggleTrace
+++ b/environment/defaults/bin/toggleTrace
@@ -7,27 +7,32 @@
 #--------------------------------
 printUsage()
 {
-    echo "Usage: `basename $0` command [-all | FileNames]
+    cat << %%USAGE%%
+
+    Usage: $(basename $0) [-h]
+           $(basename $0) <on|off> [-a|--all]
+           $(basename $0) <on|off> FileNames
 
 where
 
-    command       Must be either ON or OFF (case insensitive)
+    <on|off>     (mandatory) Specify if to set (on) or unset (off) the trace.
 
-    -all          (optional) specifies that the trace will!be set/unset for all
+    -a
+    --all         (optional) specifies that the trace will be set/unset for all
                   the source files in the current directory and its subdirs, without
                   asking for confirmation.
 
     FileName(s)   (optional) specifies to which files the trace will be set/unset. 
                   If not specified, all source files in the directory (and subdire) 
                   will be processed.
-"
+%%USAGE%%
 }
 
 
 #--------------------------------
-# Function enableTrace
+# Function trace_on
 #--------------------------------
-enableTrace()
+trace_on()
 {
     local myFile=$1
     local hasTrace=`grep '^[[:blank:]]*//.*// crpiTrace$' ${myFile}`
@@ -41,9 +46,9 @@ enableTrace()
 
 
 #--------------------------------
-# Function disableTrace
+# Function trace_off
 #--------------------------------
-disableTrace()
+trace_off()
 {
     local myFile=$1
 
@@ -67,43 +72,61 @@ if [ $# -lt 1 ]; then
     exit 1
 fi
 
+ARGS=$(getopt -o ha -l "help,all" -n $(basename $0) -- "$@")
+
+# If wrong arguments, print usage and exit
+if [[ $? -ne 0 ]]; then
+    printUsage
+    exit 1;
+fi
+
+eval set -- "$ARGS"
+
+while true; do
+    case ${1} in
+	-h|--help)
+	    printUsage
+	    exit 0
+	    ;;
+	-a|--all)
+	    echo "Toggling trace to all files in the current directory (and subdirs)."
+	    myFiles=`allSourceFiles`
+	    shift
+	    ;;
+	--)
+	    shift
+	    break
+	    ;;
+	"")
+	    # This is necessary for processing missing optional arguments 
+	    shift
+	    ;;
+    esac
+done
+
 myOption="${1}"
 shift
-myFiles="$*"
 
 if [[ -z ${myFiles} ]]; then
-    echo -e "Are you sure you want to set trace to all files in the current directory (and subdirs)? [y/n] "
-    read myAnswer
+    myFiles="$*"
+fi
 
-    case `lower ${myAnswer}` in
-        y)
-            myFiles=`allSourceFiles`
-        ;;
-        *)
-            echo "Aborting."
-            exit 0
-        ;;
-    esac
-elif [ "${myFiles}" == "-all" ]; then
-    echo "Setting trace to all files in the current directory (and subdirs)."
+if [[ -z ${myFiles} ]]; then
+    getAnswer "Are you sure you want to set trace to all files in the current directory (and subdirs)?" || remove=0
     myFiles=`allSourceFiles`
 fi
 
-echo myOption=${myOption}
+# Commands must be one on each line
+supportedCommands="on
+off"
 
-case `lower ${myOption}` in
-    on)
-        for f in $myFiles; do
-            enableTrace $f
-        done
-    ;;
-    off)
-        for f in $myFiles; do
-            disableTrace $f
-        done
-    ;;
-    *)
-        printUsage
-        echo -e "\nUnknown command \"${myOption}\""
-    ;;
-esac
+if [[ -z $(echo ${supportedCommands}|grep -e "${myOption}") ]]; then
+    printf "\nERROR!!! Unsupported command: %s\n" ${myOption}
+    printUsage
+    exit 1
+fi
+
+for f in $myFiles; do
+    trace_${myOption} $f
+done
+
