Summary: minor improvements. Details: 	1. environment/defaults/bin/cleanfiles: removed out-commented line. 	2. environment/defaults/bin/updateProductionMachine: added code to print Failed when the job fails.

diff --git a/environment/defaults/bin/updateProductionMachine b/environment/defaults/bin/updateProductionMachine
--- a/environment/defaults/bin/updateProductionMachine
+++ b/environment/defaults/bin/updateProductionMachine
@@ -134,7 +134,17 @@ fi
 rsyncCommand="rsync -azvhq"
 for userAtHost in ${usersAtHosts}; do
     printf "Updating for ${userAtHost}...  \t"
+    
     ssh -A ${userAtHost} "mkdir -p '${targetConfigDir}'" > /dev/null 2>&1
+    if [[ $? -ne 0 ]]; then
+        printf "[Failed]\n"
+        continue
+    fi
+    
     ${rsyncCommand} /mnt/config/RONIN/*.csv ${userAtHost}:${targetConfigDir} > /dev/null 2>&1
+    if [[ $? -ne 0 ]]; then
+        printf "[Failed]\n"
+        continue
+    fi
     printf "[Done]\n"
 done
